# Generated by Django 4.1.7 on 2023-03-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_datedcompleted_task_datecompleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="description",
            new_name="Coordenadas",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="Medidor",
        ),
    ]
