# Generated by Django 4.1.7 on 2023-03-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_description_task_coordenadas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="datecompleted",
        ),
    ]
