# Generated by Django 4.1.7 on 2023-03-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_datecompleted_alter_task_medidor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="Coordenadas",
            field=models.IntegerField(max_length=1000),
        ),
    ]
