# Generated by Django 4.1.7 on 2023-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_coordenadas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="Coordenadas",
            field=models.IntegerField(),
        ),
    ]
