# Generated by Django 4.1.7 on 2023-03-28 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0008_task_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="Coordenadas",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="Medidor",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
