# Generated by Django 4.1.7 on 2023-03-29 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0009_alter_task_coordenadas_alter_task_medidor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="Coordenadas",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="Medidor",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
